baseURL = 'https://knx-apps.github.io/'
languageCode = 'en-us'
title = 'KNX Apps Wiki'
theme = "hugo-book"

[params]
  BookSection = "/"
  
[markup]
  [markup.highlight]
    style = "emacs"  # pygments emacs
    lineNos = true
    noClasses = true